### ISSUE TITLE
[bug] missed contnet after \n sometimes

### ISSUE THREAD

**Issue by abhishekyelley** [linuxdotexe/boxdp#5]
Review content from https://letterboxd.com/kenough_/film/petta/1/ is
"wammala, ithaan da cinema.\n- martin scorsese"
but the part after \n seems to be ignored.

Image:
![Petta Review](https://github.com/linuxdotexe/boxdp/assets/94790503/43e1d836-0f75-4534-a6d2-835d24a98879 "Petta Review")

although not sure if \n is the cause of the issue because there is a case where the text on image seems to be fine despite multiple \n
Review content from https://letterboxd.com/harsha5773/film/salaar-part-1-ceasefire/1/ is
"story build cheyyalante ila \ndrama potray cheyyalante ila \nsound apt ga kottali ante ila\ncut out ni vadalante ila\nelivation ivvali ante ila"

Image:
![Salaar Review](https://github.com/linuxdotexe/boxdp/assets/94790503/5129e46a-ee73-4ec9-92b2-337594f9e4ab "Salaar Review")

**Comment by linuxdotexe** [comment]
In the Petta review, the first line is in a blockquote HTML element. Maybe that had some effect on it.

And do we really need to configure the template for long reviews? People know if their reviews are image-friendly when they look at the image right?

**Comment by abhishekyelley** [comment]
> People know if their reviews are image-friendly when they look at the image right?

People act like they're 5

**Comment by abhishekyelley** [comment]
> In the Petta review, the first line is in a blockquote HTML element. Maybe that had some effect on it.

But the response is a string right? It's just text.

**Comment by linuxdotexe** [comment]
> But the response is a string right? It's just text.

you make sense, senpai. should i convert `/n` to `<br/>`?

**Comment by abhishekyelley** [comment]
Ideally yes. Ignoring /n is also fine I guess.

**Comment by linuxdotexe** [comment]
> Ideally yes. Ignoring /n is also fine I guess.

it is already ignoring. let's do a poll after we get 10 users lol

**Comment by linuxdotexe** [comment]
currently displaying reviewDesc, not reviewContent.
